# Generated by Django 3.1.12 on 2025-12-13 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('file', models.CharField(max_length=400)),
                ('video', models.CharField(max_length=400)),
                ('is_cardiac', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('bmi', models.CharField(max_length=50)),
                ('bp', models.CharField(max_length=50)),
                ('cholestrol', models.CharField(max_length=50)),
                ('sugar_level', models.CharField(max_length=50)),
                ('thyroid_status', models.CharField(max_length=50)),
                ('vitamin_d_level', models.CharField(max_length=50)),
                ('smoking', models.CharField(max_length=50)),
                ('alcohol_consumption', models.CharField(max_length=50)),
                ('physical_activity_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('content', models.CharField(max_length=500)),
                ('photo', models.CharField(max_length=400)),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feedback', models.CharField(max_length=200)),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Facial_emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('emotion', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=400)),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaint', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('content', models.CharField(max_length=500)),
                ('POSTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.posts')),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.CharField(max_length=200)),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
