# Generated by Django 3.1.12 on 2025-12-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='district',
        ),
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='users',
            name='state',
        ),
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='post',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
